const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "263 71 803 6108"
const SESSION_ID = "PRABATH-MD~qAslGbgA#jajAZQJXt4IydHWBOxxhrnu7labSAttYNX5L9YEGMbI"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
